### ISSUE TITLE
Method _validateLevelId() is not future-proof

### ISSUE THREAD

**Issue by adam-coster** [jajdp/Shenanibot-public#21]
https://github.com/jajdp/Shenanibot-public/blob/436c2184b57ae716e1a5dd3e91299dadfbde6002/src/bot/index.js#L244

While it's currently true that `leveId`s are exactly 7 characters, there is no guarantee that that will always be true.

Further, the validator *only* checks length.

A length range, plus exclusion of definitely-incorrect characters, will be more robust and future-proof. For example:

```js
  _validateLevelId(id) {
    const response = {valid:false, response: `${id} is not a valid level code. "};
    if (id.length < 7 || id.length > 10) {
      response.response += "Invalid length.";
    }
    else if( ! id.match(/^[a-z0-9]+$/)){
      response.response += "Invalid characters.";
    }
    else{
      response.valid = true;
    }
    return response;
  }
```

**Comment by madelsberger** [comment]
I agree that adding validation rules for invalid characters might be a nice touch, though I would want the message to still be very specific about what was wrong (e.g. "invalid character: $" instead of just "invalid characters").

Regarding the length: As a ShenaniBot user, I do not want this change in behavior - so if it is patched in, I would ask that it be done via configuration so that I can avoid having to maintain persistent differences in my fork. I want my bot to warn the user if the length isn't currently valid, regardless of whether we speculate that the length might someday become valid.

(Also, as a developer I would say: YAGNI.  While we have no guarantee that codes will always be 7 digits, we also have no reason to think they won't.  Every person on Earth could submit about 10 levels before the pool of 7-digit codes were exhausted, and I hear a few of them don't play LevelHead though I can't imagine why.  Anyway, if the level id format changes we'll know and the change can be made then.)

**Comment by adam-coster** [comment]
Agreed, specific messages are always better!

And fair enough on the length issue.
